spring.application.name=product-service
spring.data.mongodb.uri=mongodb://root:password@localhost:27017/product-service?authSource=admin
eureka.client.service-url.defaultZone= http://eureka:password@localhost:8761/eureka
server.port=0
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=localhost
spring.zipkin.base-url=http://localhost:9411
<<<<<<< HEAD
management.tracing.sampling.probability=1.0

#Actuator promotheous endpoints
management.endpoints.web.exposure.include= prometheus
=======
management.tracing.sampling.probability=1.0
>>>>>>> 896dae3babccd8c5a2fe3fcfac0c83b210b7d3ea
